export const ARTICLES = [
  {
    id: "a1",
    kind: "feature",
    category: "Case Study",
    title: "Reimagining citizen onboarding for Estonia's e-Residency 2.0",
    dek: "How our service design team cut the application flow from 14 steps to 4 — and what we learned about trust along the way.",
    author: "Liisa Tamm",
    authorInitials: "LT",
    date: "Apr 28, 2026",
    readTime: "8 min",
    cover: "linear-gradient(135deg,#3AFF3E 0%,#01963A 70%,#003E18 100%)",
    coverPattern: "grid",
    tags: ["Service Design", "Public Sector"],
  },
  {
    id: "a2",
    kind: "standard",
    category: "Tool Experiment",
    title: "We rebuilt our wireframe library inside Claude — here's the verdict",
    dek: "Three weeks, 40 components, one very tired prompt engineer.",
    author: "Mark Sepp",
    authorInitials: "MS",
    date: "Apr 24, 2026",
    readTime: "5 min",
    cover: "#0B0F0C",
    coverPattern: "stripes",
    tags: ["AI", "Tooling"],
  },
  {
    id: "a3",
    kind: "standard",
    category: "Process",
    title: "Discovery sprints, but make them three days",
    dek: "Our compressed playbook for clients who can't afford a full week.",
    author: "Anna Mets",
    authorInitials: "AM",
    date: "Apr 22, 2026",
    readTime: "6 min",
    cover: "#FAF6E8",
    coverPattern: "dots",
    tags: ["Process", "Service Design"],
  },
  {
    id: "a4",
    kind: "standard",
    category: "Team News",
    title: "Welcome Marek, Ines, and Toomas to the design team",
    dek: "Three new faces, two new offices, and one very full Tallinn studio.",
    author: "Editorial",
    authorInitials: "ED",
    date: "Apr 19, 2026",
    readTime: "2 min",
    cover: "#3AFF3E",
    coverPattern: "confetti",
    tags: ["Team"],
  },
  {
    id: "a5",
    kind: "standard",
    category: "Learning",
    title: "Notes from Config 2026: agentic UX is the next frontier",
    dek: "Five takeaways the whole team should care about, from someone who took 73 pages of notes.",
    author: "Priit Vaher",
    authorInitials: "PV",
    date: "Apr 16, 2026",
    readTime: "7 min",
    cover: "linear-gradient(135deg,#FF8AE6 0%,#7A4CFF 100%)",
    coverPattern: "blob",
    tags: ["Learning", "AI"],
  },
  {
    id: "a6",
    kind: "standard",
    category: "Case Study",
    title: "Designing for trust in a national health record",
    dek: "Why we ditched the dashboard pattern and what replaced it.",
    author: "Kerli Roos",
    authorInitials: "KR",
    date: "Apr 12, 2026",
    readTime: "10 min",
    cover: "#011A0A",
    coverPattern: "ring",
    tags: ["Healthcare", "Service Design"],
  },
  {
    id: "a7",
    kind: "standard",
    category: "Tool Experiment",
    title: "Claude Code as a junior front-end designer: a one-month diary",
    dek: "What worked, what broke, and the prompts we kept coming back to.",
    author: "Toomas Lepp",
    authorInitials: "TL",
    date: "Apr 09, 2026",
    readTime: "9 min",
    cover: "#F2EFE3",
    coverPattern: "code",
    tags: ["AI", "Engineering"],
  },
  {
    id: "a8",
    kind: "standard",
    category: "Process",
    title: "How we critique each other's work without ruining Friday",
    dek: "A lightweight critique format the team actually shows up for.",
    author: "Ines Kask",
    authorInitials: "IK",
    date: "Apr 04, 2026",
    readTime: "4 min",
    cover: "#FFD23F",
    coverPattern: "scribble",
    tags: ["Process", "Team"],
  },
  {
    id: "a9",
    kind: "standard",
    category: "Learning",
    title: "Workshop recap: accessibility audits in 90 minutes",
    dek: "Our internal workshop, condensed into a doc you can actually use on Monday.",
    author: "Marek Põld",
    authorInitials: "MP",
    date: "Mar 30, 2026",
    readTime: "6 min",
    cover: "#0070F3",
    coverPattern: "lines",
    tags: ["Accessibility", "Learning"],
  },
  {
    id: "a10",
    kind: "standard",
    category: "Case Study",
    title: "From 11 forms to 1: rebuilding tax filing for SMEs",
    dek: "A six-month transformation, told in screenshots and screen recordings.",
    author: "Hanna Mägi",
    authorInitials: "HM",
    date: "Mar 26, 2026",
    readTime: "12 min",
    cover: "linear-gradient(135deg,#01963A 0%,#0B0F0C 100%)",
    coverPattern: "grid",
    tags: ["Public Sector", "Case Study"],
  },
];

export const PROMPTS = [
  {
    id: "p1",
    title: "Generate accessibility audit checklist from a screenshot",
    body: "You are a senior accessibility specialist following WCAG 2.2 AA. Look at the attached screenshot and produce an accessibility audit. For each issue: (1) WCAG criterion, (2) severity (blocker/major/minor), (3) where on the screen, (4) a concrete fix written for a designer. Group by severity. Be specific. Don't pad with generalities.",
    tool: "Claude",
    category: "Audit",
    tags: ["accessibility", "wcag", "review"],
    author: "Marek Põld",
    authorInitials: "MP",
    date: "Apr 28, 2026",
    notes: "Works best with full-page screenshots. For long pages, chunk into 3–4 sections.",
    favorites: 14,
  },
  {
    id: "p2",
    title: "Turn a Figma flow into stakeholder-friendly narrative",
    body: "I'll paste a list of screen names and short descriptions from a Figma flow. Rewrite this as a 1-page narrative for a non-designer stakeholder, in plain language. Lead with the user's goal, name each step, and end with what success looks like. No jargon. Max 250 words.",
    tool: "ChatGPT",
    category: "Storytelling",
    tags: ["stakeholders", "writing", "presentation"],
    author: "Liisa Tamm",
    authorInitials: "LT",
    date: "Apr 25, 2026",
    notes: "Pairs nicely with Loom — record yourself reading it.",
    favorites: 22,
  },
  {
    id: "p3",
    title: "Component library audit prompt",
    body: "Act as a design systems lead. Given the attached list of components, identify: (1) duplicates or near-duplicates, (2) gaps where common patterns are missing, (3) naming inconsistencies. Output a table sorted by impact. Be skeptical and direct — call out tech debt, don't sugarcoat.",
    tool: "Claude",
    category: "Audit",
    tags: ["design-system", "components", "review"],
    author: "Hanna Mägi",
    authorInitials: "HM",
    date: "Apr 22, 2026",
    notes: "Feed it your Storybook export or a Figma component panel screenshot.",
    favorites: 9,
  },
  {
    id: "p4",
    title: "Brutal first-pass copy critique",
    body: "You are a senior content designer who's seen everything. Critique the attached UI copy. Be direct — no hedging, no 'consider'. For every line: keep, cut, or rewrite. If rewriting, give 2 options. Optimize for: clarity > brevity > tone. Don't preserve the structure if it's wrong.",
    tool: "Claude",
    category: "Copy",
    tags: ["content-design", "writing", "review"],
    author: "Anna Mets",
    authorInitials: "AM",
    date: "Apr 20, 2026",
    notes: "I prefix with 'B2G fintech, expert users' for context.",
    favorites: 31,
  },
  {
    id: "p5",
    title: "Generate 5 visual directions from a brand brief",
    body: "Read the attached brand brief. Propose 5 distinct visual directions. For each: a name, a 1-sentence concept, 3 mood-board references (real ones — designers, films, products), a primary + 2 accent colors with hex, a typeface pairing, and a 1-line risk. Spread the options — don't make them variations of one idea.",
    tool: "Claude",
    category: "Exploration",
    tags: ["branding", "ideation", "visual"],
    author: "Kerli Roos",
    authorInitials: "KR",
    date: "Apr 18, 2026",
    notes: "Real references > made-up ones. If it hallucinates, push back: 'cite real designers'.",
    favorites: 27,
  },
  {
    id: "p6",
    title: "Refactor my React component into Tailwind + shadcn",
    body: "Refactor the attached component to use Tailwind CSS and shadcn/ui primitives. Preserve all behavior and accessibility. Use semantic HTML. Don't add features. Don't reorganize logic unless the refactor demands it. Output: full file, then a 3-line summary of what changed.",
    tool: "Claude Code",
    category: "Engineering",
    tags: ["react", "tailwind", "refactor"],
    author: "Toomas Lepp",
    authorInitials: "TL",
    date: "Apr 15, 2026",
    notes: "Pin the shadcn version in the prompt — saves a round-trip.",
    favorites: 18,
  },
  {
    id: "p7",
    title: "Workshop facilitation plan from a fuzzy goal",
    body: "I need to run a workshop. Goal: [GOAL]. Participants: [N people, roles]. Time: [hours]. Output a minute-by-minute facilitation plan: opener, 2–3 working blocks with exercises, energy checks, and a closer. For each exercise, include: setup, instructions to read aloud, materials, output. Keep it tight — assume people are busy.",
    tool: "ChatGPT",
    category: "Facilitation",
    tags: ["workshop", "service-design", "process"],
    author: "Liisa Tamm",
    authorInitials: "LT",
    date: "Apr 12, 2026",
    notes: "Best prompt for remote workshops — switches to Miro instructions if you ask.",
    favorites: 24,
  },
  {
    id: "p8",
    title: "Draft a research debrief from raw notes",
    body: "I'll paste raw notes from 5 user interviews. Synthesize: (1) top 5 themes with supporting quotes, (2) surprising findings, (3) opportunities ranked by impact and feasibility, (4) what we still don't know. No padding. Quote verbatim. If a theme has only 1 supporting quote, flag it as weak.",
    tool: "Claude",
    category: "Research",
    tags: ["user-research", "synthesis", "interviews"],
    author: "Anna Mets",
    authorInitials: "AM",
    date: "Apr 09, 2026",
    notes: "Run twice with the same input to spot what shifts — those are your weak themes.",
    favorites: 35,
  },
  {
    id: "p9",
    title: "Persona brief that's actually useful",
    body: "Generate a persona for [DOMAIN, USER TYPE]. Include: name, role, what they're trying to do today (not their life story), 3 jobs-to-be-done, top 3 frustrations with current tools, 1 line about their context (where, when, with whom). Skip stock-photo descriptions, hobbies, and 'tech-savvy: 7/10' bars.",
    tool: "ChatGPT",
    category: "Research",
    tags: ["personas", "user-research"],
    author: "Ines Kask",
    authorInitials: "IK",
    date: "Apr 06, 2026",
    notes: "I always strip out the demographics block before sharing.",
    favorites: 12,
  },
  {
    id: "p10",
    title: "Sanity-check a UX flow before shipping",
    body: "You're a skeptical principal designer reviewing a flow before launch. Given the attached screens (in order), identify: (1) dead ends, (2) decisions the user can't reverse, (3) unclear feedback states, (4) places where load/empty/error states are missing. Be specific and brief. Don't restate what's working.",
    tool: "Claude",
    category: "Audit",
    tags: ["review", "flows", "qa"],
    author: "Mark Sepp",
    authorInitials: "MS",
    date: "Apr 03, 2026",
    notes: "Worth its weight in gold the day before launch.",
    favorites: 41,
  },
  {
    id: "p11",
    title: "Translate a design decision into engineering language",
    body: "I'll describe a design decision. Rewrite it as a technical proposal an engineer can act on: user-visible behavior, edge cases, state machine if relevant, accessibility requirements, what's out of scope. No design jargon. No 'delight'.",
    tool: "Claude",
    category: "Engineering",
    tags: ["handoff", "writing", "engineering"],
    author: "Toomas Lepp",
    authorInitials: "TL",
    date: "Mar 30, 2026",
    notes: "Saved me ~3 standups a week.",
    favorites: 19,
  },
  {
    id: "p12",
    title: "Generate variations of a single button",
    body: "Generate 8 visual variations of a primary button for a [BRAND TONE] product. Vary: weight, radius, border, fill, shadow, label style. For each, give CSS + a 1-line rationale. Lean into the brand — don't default to neutral. Skip gradients unless the brand demands them.",
    tool: "Claude",
    category: "Exploration",
    tags: ["visual", "components", "ideation"],
    author: "Mark Sepp",
    authorInitials: "MS",
    date: "Mar 26, 2026",
    notes: "Run with brand-tone words like 'precise, civic, restrained' for sharper outputs.",
    favorites: 16,
  },
];

export const TEAM = {
  "Service Design": [
    {
      id: "t1",
      name: "Pärt Ojamaa",
      initials: "PO",
      role: "Senior Service Designer",
      office: "Tartu",
      officeFreq: 70,
      joined: "4 years ago",
      hobbies: ["Open-water swimming", "Bread baking", "Birdwatching"],
      funFact: "Once led a workshop in 5 languages at the same time.",
      contact: "Slack DM or coffee in the kitchen",
      introExtra: 35,
      avatar: "#3AFF3E",
    },
    {
      id: "t2",
      name: "Sten Rõngelep",
      initials: "SR",
      role: "Senior Service Designer",
      office: "Tallinn",
      officeFreq: 50,
      joined: "2 years ago",
      hobbies: ["Tango", "Cycling", "Pottery"],
      funFact: "Holds the office record for most sticky notes used in a single workshop (4,200).",
      contact: "Slack — async preferred",
      introExtra: 70,
      avatar: "#FFD23F",
    },
    {
      id: "t3",
      name: "Derin Baykal",
      initials: "DB",
      role: "Service Designer",
      office: "Berlin",
      officeFreq: 90,
      joined: "1 year ago",
      hobbies: ["Mushroom foraging", "Board games", "Field recording"],
      funFact: "Has a podcast about queueing theory. 4 listeners. All family.",
      contact: "Email or Slack",
      introExtra: 25,
      avatar: "#7A4CFF",
    },
    {
      id: "t4",
      name: "Karin Tikerpe",
      initials: "KT",
      role: "Group Design Lead",
      office: "Tallinn",
      officeFreq: 40,
      joined: "9 years 0 months",
      joinedDate: "2017-05",
      hobbies: ["Reading books", "sports", "making homevideos"],
      funFact: "I have most probably broken all the bones in my body during childhood 😅 I was an active child and believed I can do anything. I still do 😊 but take a bit more caution on the active stuff.",
      contact: "Teams DM",
      introExtra: 55,
      avatar: "#FF8AE6",
    },
  ],
  "Product Design": [
    {
      id: "t5",
      name: "Mari-Liis Kärsten",
      initials: "MK",
      role: "Senior Product Designer",
      office: "Tartu",
      officeFreq: 60,
      joined: "5 years ago",
      hobbies: ["Trail running", "Espresso", "Modular synths"],
      funFact: "Owns 14 keyboards. Uses one.",
      contact: "Slack any time, even weekends — please don't",
      introExtra: 60,
      avatar: "#01963A",
    },
    {
      id: "t6",
      name: "Martin Babic",
      initials: "MB",
      role: "Senior Product Designer",
      office: "Tallinn",
      officeFreq: 80,
      joined: "3 years ago",
      hobbies: ["Cross-country skiing", "Linocut", "Cooking Korean food"],
      funFact: "Was a professional ice-dancer until he was 19.",
      contact: "Coffee — book his calendar",
      introExtra: 45,
      avatar: "#0070F3",
    },
    {
      id: "t7",
      name: "Raul-Kristjan Piiroja",
      initials: "RP",
      role: "Senior Product Designer",
      office: "Tallinn",
      officeFreq: 55,
      joined: "2 years ago",
      hobbies: ["Vinyl collecting", "Hiking", "Watercolor"],
      funFact: "Can name every typeface used by the Estonian government since 2003.",
      contact: "Slack DM with specifics",
      introExtra: 40,
      avatar: "#FF6B35",
    },
    {
      id: "t8",
      name: "Oskar Mihhailov",
      initials: "OM",
      role: "Senior Product Designer",
      office: "Tallinn",
      officeFreq: 100,
      joined: "1 year ago",
      hobbies: ["Long-distance cycling", "Audiobooks", "Chess"],
      funFact: "Cycled Tallinn → Lisbon over one summer.",
      contact: "Email — keeps Slack on Do Not Disturb",
      introExtra: 30,
      avatar: "#003E18",
    },
    {
      id: "t8b",
      name: "Saara Vällik",
      initials: "SV",
      role: "Product Designer",
      office: "Tallinn",
      officeFreq: 70,
      joined: "6 months ago",
      hobbies: ["Roller skating", "Film photography", "Fermenting things"],
      funFact: "Has visited every art museum in Tallinn — twice.",
      contact: "Slack DM, prefers Tuesdays for deep work",
      introExtra: 50,
      avatar: "#FFD23F",
    },
  ],
  "UI Development": [
    {
      id: "t9",
      name: "Aleksandr Beliaev",
      initials: "AB",
      role: "Lead UI Engineer",
      office: "Tallinn",
      officeFreq: 30,
      joined: "6 years ago",
      hobbies: ["Sailing", "Brewing", "Tinkering with old motorcycles"],
      funFact: "Built his first website in 1998. It still works.",
      contact: "GitHub, Slack, beer",
      introExtra: 50,
      avatar: "#3AFF3E",
    },
    {
      id: "t10",
      name: "Ekaterina Loginova",
      initials: "EL",
      role: "Senior UI Engineer",
      office: "Riga",
      officeFreq: 65,
      joined: "3 years ago",
      hobbies: ["Yoga", "Travel photography", "Houseplants (47 of them)"],
      funFact: "Speaks 6 languages. Apologizes in all of them.",
      contact: "Slack — fastest response of anyone on the team",
      introExtra: 75,
      avatar: "#FFD23F",
    },
    {
      id: "t11",
      name: "Jordan Jorš",
      initials: "JJ",
      role: "UI Engineer",
      office: "Tallinn",
      officeFreq: 75,
      joined: "1 year ago",
      hobbies: ["Skateboarding", "3D printing", "Lo-fi production"],
      funFact: "Once shipped a fix from a tent in the Lahemaa forest.",
      contact: "Slack or in person — usually near the snacks",
      introExtra: 65,
      avatar: "#7A4CFF",
    },
  ],
};

export const CHALLENGES = {
  active: {
    id: "c-may-2026",
    title: "Create a skeuomorphic UI for an application or website you use daily (desktop or mobile)",
    status: "Active",
    deadline: "2026-05-31T23:59:00",
    month: "May 2026",
  },
  previous: [
    {
      id: "c-apr-2026",
      date: "April 2, 2026",
      title: "Create a simple dating app screen with a design system used in Nortal but never by yourself",
      winner: { name: "Oskar", avatar: "#FF8AE6" },
    },
    {
      id: "c-mar-2026",
      date: "March 5, 2026",
      title: "Create an “out of the box” Save icon",
      winner: { name: "Hiep", avatar: "#3AFF3E" },
    },
    {
      id: "c-feb-2026",
      date: "February 5, 2026",
      title: "Create a landing illustration for a lifestyle app that represents your idea of work-life balance",
      winner: { name: "Mari-Liis", avatar: "#FFD23F" },
    },
  ],
  scoring: { first: 10, second: 6, third: 4, entry: 2 },
  leaderboard: [
    { rank: 1, name: "Martin", avatar: "#7A4CFF", entries: 3, first: 0, second: 2, third: 0, points: 14 },
    { rank: 2, name: "Oskar", avatar: "#FF8AE6", entries: 3, first: 1, second: 0, third: 0, points: 14 },
    { rank: 3, name: "Hiep", avatar: "#3AFF3E", entries: 3, first: 1, second: 0, third: 1, points: 14 },
    { rank: 4, name: "Saara", avatar: "#FF6B35", entries: 3, first: 0, second: 1, third: 1, points: 14 },
    { rank: 5, name: "Mari-Liis", avatar: "#FFD23F", entries: 2, first: 1, second: 0, third: 0, points: 10 },
    { rank: 6, name: "Raul", avatar: "#0EA5E9", entries: 3, first: 0, second: 0, third: 1, points: 8 },
    { rank: 7, name: "Anisa", avatar: "#A855F7", entries: 0, first: 0, second: 0, third: 0, points: 0 },
    { rank: 8, name: "Natalie", avatar: "#EC4899", entries: 0, first: 0, second: 0, third: 0, points: 0 },
    { rank: 9, name: "Greta", avatar: "#10B981", entries: 0, first: 0, second: 0, third: 0, points: 0 },
    { rank: 10, name: "Derin", avatar: "#F59E0B", entries: 0, first: 0, second: 0, third: 0, points: 0 },
    { rank: 11, name: "Sebastian", avatar: "#64748B", entries: 0, first: 0, second: 0, third: 0, points: 0 },
  ],
  designers: [
    { name: "Mari-Liis", avatar: "#FFD23F", location: "Tartu, Estonia", since: "Nov 2016", entries: 8, wins: 2, participation: 47, status: "active" },
    { name: "Greta", avatar: "#10B981", location: "Berlin, Germany", since: "Apr 2018", entries: 7, wins: 0, participation: 41, status: "active" },
    { name: "Raul", avatar: "#0EA5E9", location: "Tallinn, Estonia", since: "Nov 2020", entries: 16, wins: 2, participation: 94, status: "active" },
    { name: "Martin", avatar: "#7A4CFF", location: "Tallinn, Estonia", since: "Jun 2021", entries: 17, wins: 4, participation: 100, status: "active", trophies: ["2023", "2025"] },
    { name: "Hiep", avatar: "#3AFF3E", location: "Helsinki, Finland", since: "Jul 2021", entries: 15, wins: 5, participation: 88, status: "active", trophies: ["2024"] },
    { name: "Derin", avatar: "#F59E0B", location: "Berlin, Germany", since: "Oct 2022", entries: 2, wins: 0, participation: 13, status: "active" },
    { name: "Natalie", avatar: "#EC4899", location: "Dresden, Germany", since: "Mar 2023", entries: 4, wins: 0, participation: 24, status: "active" },
    { name: "Saara", avatar: "#FF6B35", location: "Tallinn, Estonia", since: "Sept 2023", entries: 9, wins: 1, participation: 53, status: "active" },
    { name: "Anisa", avatar: "#A855F7", location: "Muscat, Oman", since: "Nov 2023", entries: 4, wins: 1, participation: 25, status: "active" },
    { name: "Sebastian", avatar: "#64748B", location: "Potsdam, Germany", since: "May 2025", entries: 2, wins: 0, participation: 17, status: "active" },
    { name: "Oskar", avatar: "#FF8AE6", location: "Tallinn, Estonia", since: "Aug 2025", entries: 7, wins: 2, participation: 78, status: "active" },
    { name: "Mikko", avatar: "#94A3B8", location: "Last seen Dec 2024", since: null, entries: 1, wins: 0, participation: 50, status: "former" },
    { name: "Taha", avatar: "#94A3B8", location: "Last seen Aug 2025", since: null, entries: 1, wins: 0, participation: 13, status: "former" },
  ],
};
